## 1.Write a Python Program to Add Two Matrices?

In [102]:
# Program to add two matrices using list comprehension

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[X[i][j] + Y[i][j]  for j in range(len(X[0]))] for i in range(len(X))]

for r in result:
   print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [19]:
import numpy as np

In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
def add_matrix(one,two):
    """ This function adds two arrays and gives the result 

    """
    result=np.zeros((len(one),len(two)))
    for i in range(len(one)):
        for j in range(len(one[0])):
            result[i][j]=one[i][j] + two[i][j]
    return result
            

In [26]:
add_matrix(X,Y)

array([[17., 15.,  4.],
       [10., 12.,  9.],
       [11., 13., 18.]])

## 2.Write a Python Program to Multiply Two Matrices?

In [68]:
class Operations:
    
    def __init__(self,A,B):
        print("We are in init  Function")
        print(f"the Input arrays are {A} \n and{B}")
        self.A = A
        self.B = B
    def Multiplication(self):
        print("\n")
        """Performs Multiplication function """
        print("Multiplication of the two results is ")
        result=np.zeros((len(self.A),len(self.B)))
        for i in range(len(self.A)):
            for j in range(len(self.A[0])):
                result[i][j]=self.A[i][j] * self.B[i][j]
        print(result)
        
    def add_matrix(self):
        """ This function adds two arrays and gives the result"""
        print("Addition of the two arrays is ")
        result=np.zeros((len(self.A),len(self.B)))
        for i in range(len(self.A)):
            for j in range(len(self.A[0])):
                result[i][j]=self.A[i][j] + self.B[i][j]
        print(result)

    
if __name__=="__main__":
    obj = Operations(X,Y)
    obj.Multiplication()
    obj.add_matrix()

We are in init  Function
the Input arrays are [[12, 7, 3], [4, 5, 6], [7, 8, 9]] 
 and[[5, 8, 1], [6, 7, 3], [4, 5, 9]]


Multiplication of the two results is 
[[60. 56.  3.]
 [24. 35. 18.]
 [28. 40. 81.]]
Addition of the two arrays is 
[[17. 15.  4.]
 [10. 12.  9.]
 [11. 13. 18.]]


### 3.Write a Python Program to Transpose a Matrix?

In [56]:
"""Transpose of a matrix is obtained by changing rows to columns
and columns to rows. In other words,
transpose of A[][] is obtained by changing A[i][j] to A[j][i]. 

"""

def Transpose(A):
    reverse=np.zeros((len(X),len(X[0])))
    print(f"Initial array was")
    print(A)
    for i in range(len(A)):
        for j in range(len(A[0])):
            reverse[i][j]=A[j][i]
    print(reverse)
        

if __name__=="__main__":
    obj=Transpose(Y)
    
    
    

Initial array was
[[5, 8, 1], [6, 7, 3], [4, 5, 9]]
[[5. 6. 4.]
 [8. 7. 5.]
 [1. 3. 9.]]


In [49]:

print(reverse)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## 4.Write a Python Program to Sort Words in Alphabetic Order?

In [101]:
#def sort_words(paragraph):
paragraph='''The string module dates from the earliest versions of Python. 
In version 2.0, many of the functions previously implemented only in the module were moved to ...'''
li=paragraph.split()
li=sorted(li)
print(li)

['...', '2.0,', 'In', 'Python.', 'The', 'dates', 'earliest', 'from', 'functions', 'implemented', 'in', 'many', 'module', 'module', 'moved', 'of', 'of', 'only', 'previously', 'string', 'the', 'the', 'the', 'to', 'version', 'versions', 'were']


## 5.Write a Python Program to Remove Punctuation From a String?

In [97]:
import string 
def remove_puntuations(A):
    print(f"The puntuations given in the string module are {string.punctuation}")
    punctuations='!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'
    for elements in A:
        if elements in punctuations:
            A =A.replace(elements,"")
    return A
remove_puntuations('!"#$%&\'()Rajesh Hugar~",",,,*&#$#^&(**)')

The puntuations given in the string module are !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


'Rajesh Hugar'